In [56]:
import numpy as np

Create a array

In [57]:
data = np.arange(10)
print (data.shape)
data

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
data = data.reshape(2,5)
print (data.shape)
data

(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
data_1 = np.ones([3,3])
print (type(data_1))
print (data_1)

<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [135]:
data_1 = np.zeros([3,3])
print (data_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [61]:
data = np.eye(3,3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
data =np.diag((1,2,3))
data

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [136]:
data = np.empty([3,3])
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
data = np.random.rand(3,3)
print (data)

[[0.76001944 0.76014203 0.69006988]
 [0.43712794 0.80168502 0.74677639]
 [0.92035521 0.37477331 0.47287165]]


In [64]:
data = np.array([[1,2,3],[2,3,4],[3,4,5]])
data

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [65]:
data_list = list(range(9))
data = np.array(data_list).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Matrix Operation

In [66]:
a = np.arange(3)
print (a)
a.shape

[0 1 2]


(3,)

In [67]:
b = a.T
print (b)
b.shape

[0 1 2]


(3,)

In [68]:
a = a.reshape(1,3) # row first, column second
print (a)
a.shape

[[0 1 2]]


(1, 3)

In [69]:
b = a.T
print (b)
b.shape

[[0]
 [1]
 [2]]


(3, 1)

In [70]:
c = np.dot(b,a)
c

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [71]:
c = b @ a
c

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [72]:
c = c + np.ones([3,3])
c

array([[1., 1., 1.],
       [1., 2., 3.],
       [1., 3., 5.]])

In [73]:
c ** 2

array([[ 1.,  1.,  1.],
       [ 1.,  4.,  9.],
       [ 1.,  9., 25.]])

In [74]:
d = c * c
d

array([[ 1.,  1.,  1.],
       [ 1.,  4.,  9.],
       [ 1.,  9., 25.]])

In [94]:
a = np.random.rand(3,3)
a

array([[0.2667073 , 0.40904997, 0.74566646],
       [0.31699809, 0.24457967, 0.8314453 ],
       [0.06506728, 0.45162315, 0.65011276]])

In [95]:

all_max = a.max()
x_max = a.max(axis = 0) # axis means along which axis
y_max = a.max(axis = 1)
print (all_max,x_max,y_max)

0.8314452962368343 [0.31699809 0.45162315 0.8314453 ] [0.74566646 0.8314453  0.65011276]


In [97]:
all_max_arg = a.argmax()
x_max_arg = a.argmax(axis = 0)
print (all_max_arg, x_max_arg)

5 [1 2 1]


In [121]:
a = np.random.rand(12)
a

array([0.10468748, 0.07403991, 0.24936496, 0.20668834, 0.0232304 ,
       0.02075118, 0.41214989, 0.19854969, 0.50006203, 0.14111979,
       0.2025191 , 0.0269651 ])

In [123]:
ind = a.argsort()
ind

array([ 5,  4, 11,  1,  0,  9,  7, 10,  3,  2,  6,  8], dtype=int64)

In [120]:
a.sort()
a

array([0.05373398, 0.23460002, 0.24023048, 0.37094078, 0.4317469 ,
       0.46284153, 0.56538641, 0.60010524, 0.71467932, 0.73202828,
       0.79012495, 0.95240437])

Indexing, Slicing and Iterating

In [80]:
b= a[:,2]
b

array([0.17796252, 0.65149928, 0.2890341 ])

In [82]:
for row in a:
    print (row)

[0.92893031 0.46464621 0.17796252]
[0.25390472 0.87602985 0.65149928]
[0.65964098 0.71019732 0.2890341 ]


In [83]:
for element in a.flat:
    print (element)

0.9289303071267206
0.4646462094159878
0.177962518590421
0.2539047163089142
0.8760298496712924
0.6514992763677129
0.6596409774863767
0.7101973220164645
0.2890340970213311


In [85]:
a = np.random.rand(4,4)
a

array([[0.58379855, 0.14245102, 0.27714537, 0.10337657],
       [0.37516563, 0.49207191, 0.94798952, 0.62296905],
       [0.98396493, 0.88937206, 0.65539066, 0.05832903],
       [0.96499717, 0.94427867, 0.14567505, 0.12057328]])

In [87]:
b = a.reshape(8,-1)
b

array([[0.58379855, 0.14245102],
       [0.27714537, 0.10337657],
       [0.37516563, 0.49207191],
       [0.94798952, 0.62296905],
       [0.98396493, 0.88937206],
       [0.65539066, 0.05832903],
       [0.96499717, 0.94427867],
       [0.14567505, 0.12057328]])

Stacking together different arrays

In [88]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)
print (a,b)

[[0.6358644  0.54421751]
 [0.60108386 0.39502194]] [[0.54279003 0.31568792]
 [0.53448394 0.80231394]]


In [89]:
np.vstack((a,b)) # vertical stack

array([[0.6358644 , 0.54421751],
       [0.60108386, 0.39502194],
       [0.54279003, 0.31568792],
       [0.53448394, 0.80231394]])

In [90]:
np.hstack((a,b)) # horizontal stack

array([[0.6358644 , 0.54421751, 0.54279003, 0.31568792],
       [0.60108386, 0.39502194, 0.53448394, 0.80231394]])

Copies and Views

In [92]:
a = np.arange(12)
# No copy at all, different names, but share same memory address
# shape of a and data are changable via b
b= a 
# Shallow copy: shape of a doesn't change and data of a changes
c = a.view() 
# Deep copy: a's shape and data don't change
d= a.copy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Indexing with Boolean Arrays

In [100]:
a = np.random.rand(3,3)
a

array([[0.77735733, 0.78325942, 0.20491935],
       [0.4104759 , 0.08665393, 0.30595638],
       [0.77152057, 0.02170397, 0.60612012]])

In [101]:
a[[0,2],[1,2]]

array([0.78325942, 0.60612012])

In [102]:
a[a>0.5]

array([0.77735733, 0.78325942, 0.77152057, 0.60612012])

Linear Algebra

In [103]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [104]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [108]:
np.linalg.eig(a)


(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Questions

In [132]:
data = np.eye(3,3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.nonzero(data)


(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [134]:
np.any(data)

True